CREATE TABLE public.users_roles
(
    users_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    roles integer,
    CONSTRAINT fk2asnqhx8uljao0m32kmkk55av FOREIGN KEY (users_email)
        REFERENCES public.users (email) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE public.contact_emails
    ADD id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.contact_emails
    ALTER COLUMN contact_id DROP NOT NULL;

ALTER TABLE public.contact_emails
    DROP CONSTRAINT fkhxco8ferpny7ohg9plnyff96e;

ALTER TABLE public.contact_emails
    ADD CONSTRAINT email_pkey PRIMARY KEY (id);

ALTER TABLE public.contact_emails
    ADD CONSTRAINT fk85pasi49am6xyaxoph3i9rvl4 FOREIGN KEY (contact_id)
        REFERENCES public.contact (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;

ALTER TABLE public.contact_emails
    RENAME COLUMN emails TO email;

ALTER TABLE public.contact_emails
    RENAME TO email;
